### PR TITLE
Support verification state for oauth

### PR DESCRIPTION
**Pull request by nanaya**
Mirrors the one in osu-web.

- [x] ppy/osu-web#10800

### CODE REVIEW

**Review by notbakaneko — COMMENTED** [review]
maybe a good time to add `"noUncheckedIndexedAccess": true` to tsconfig? 🤔

**Comment by notbakaneko** [comment]
I didn't check to see how `length` checks affect anything yet, though 👀

**Comment by nanaya** [comment]
the one I removed here is literally the only one failed by the check. I can add it anyway I guess 🤷‍♀️ and maybe the entire strict option while at it (also no error)

**Comment by notbakaneko** [comment]
I think we can turn all the `strict` options on; I'm not sure about `noUncheckedIndexedAccess` because it turns `T[]` into `T | undefined` when accessing by index regardless of any bounds checks...

**Review by notbakaneko — APPROVED** [review]
Should be deployed after migration in ppy/osu-web#10800

**Review by peppy — APPROVED** [review]

**Pull request merged**
